config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "users/registrations"}

  resources :users, excerpt: [:create]
  root to:'welcome#index'

  get 'welcome/admin_panel', to: "welcome#admin_panel"
  get 'welcome/instructor_panel', to: 'welcome#instructor_panel'
  get 'welcome/nutritionist_panel', to: 'welcome#nutritionist_panel'
  get 'welcome/student_panel', to: 'welcome#student_panel'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :first_name, presence:true
  validates :last_name, presence:true
  validates :role, presence:true

  ROLES = %i[superadmin instructor nutriologist student]

  def superadmin?
  	role == "superadmin"
  end

  def instructor?
  	role == "instructor"
  end

  def nutritionist?
  	role == "nutritionist"
  end

  def student?
  	role == "student"
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

	def configure_permitted_parameters
	    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :role, :photo, :email, :password_confirmation, :password, :bio, :phone, :birthdate, :occupation])

      	devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :role, :photo, :email, :password_confirmation, :password, :bio, :phone, :birthdate, :occupation])
    end
end

app/controllers/users/registrations_controllers.rb
class Users::RegistrationsController < Devise::RegistrationsController 
	def create
		build_resource(sign_up_params)

	    if resource.save
	      	if resource.active_for_authentication?
		        flash[:notice] = "Bienvenido"
		        respond_with resource, :location => after_sign_up_path_for(resource)
	      	else
		        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_navigational_format?
		        expire_session_data_after_sign_in!
		        respond_with resource, :location => after_inactive_sign_up_path_for(resource)
	      	end
	    else
	    	clean_up_passwords resource
	    	respond_with resource
	    end
	end

	private

	def sign_up_params
    	devise_parameter_sanitizer.sanitize(:sign_up)
  	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update, :destroy]

	def index
	end

	def new
		@user = User.new
	end

	def show
	end

	def edit
	end

	def update
	end

	def destroy
	end

	private
		def set_user
			@user = User.find(params[:id])
			rescue ActiveRecord::RecordNotFound
				flash[:alert] = "La página que estabas buscando no existe"
				redirect_to root_url
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
	end

	def admin_panel
		@students = User.where(role: 'student')

		@instructors = User.where(role:'instructor')

		@nutritionists = User.where(role:'nutritionist')
	end

	def instructor_panel
		@students = User.where(role: 'student')
	end

	def nutritionist_panel
		@students = User.where(role: 'student')
	end

	def student_panel
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vertical</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if !user_signed_in? %>
	<%= link_to "Login", new_user_session_path %>
<% else %>
	<%= link_to "Cerrar Sesión", destroy_user_session_path %><br>
	<%= link_to "Perfil", current_user %><br>

	<% if current_user.superadmin? %>
		<%= link_to "Admin Panel", welcome_admin_panel_path %>
	<% end %>
	<% if current_user.instructor? %>
		<%= link_to "Admin Panel", welcome_instructor_panel_path %>
	<% end %>
	<% if current_user.nutritionist? %>
		<%= link_to "Admin Panel", welcome_nutritionist_panel_path %>
	<% end %>
	<% if current_user.student? %>
		<%= link_to "Admin Panel", welcome_student_panel_path %>
	<% end %>
<%end%>
	

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

	<% if @user.errors.any? %>
		<div id="error_explanation">
			<h2>No se puede guardar por: </h2>
			<ul>
			<% @user.errors.messages.values. each do |msg| %>
			<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

	<%= f.text_field :first_name, placeholder: "Nombre:" %>
	<%= f.text_field :last_name, placeholder: "Apellido:" %>
	<%= f.select(:role, ['superadmin', 'instructor', 'nutritionist', 'student']) %>

	<%= f.submit %>

<%end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<h1><%= @user.first_name %><%= @user.last_name %></h1>

<p><%= @user.role %> </p>
<p><%= @user.bio %></p>
<p><%= @user.birthdate %></p>
<p><%= @user.photo %></p>
<p><%= @user.occupation %></p>

app/views/welcome/admin_panel.html.erb
Admin Panel 

app/views/welcome/index.html.erb
Welcome Vertical

app/views/welcome/instructor_panel.html.erb
Instructor Panel

app/views/welcome/nutritionist_panel.html.erb
Nutritionist Panel

app/views/welcome/student_panel.html.erb
Student Panel